title: eamaya blog
author: Edgardo Amaya
email: eamaya82@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A successful Full Stack Web Developer is not a  
  superhuman ability to do everything, but rather, to  
  understand everythin and perhaps even more  
  importantly, they’ll be able to effectively  
  communicate with all stakeholders in the stack.

# social links
twitter_username: @eamaya82
github_username:  eamaya82

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
